#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width         0
bspc config window_gap          20
bspc config top_padding         10
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# set resolution (uw)
xrandr --output DP-2 --mode 5120x2160

# autostart applications
sxhkd &
picom --config ~/.config/picom/picom.conf &
nitrogen --restore &
dunst &
polybar &
