#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width         2
bspc config window_gap          25
bspc config top_padding         15
bspc config bottom_padding      10
bspc config left_padding        10
bspc config right_padding       10
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#363a4f"
bspc config focused_border_color "#363a4f"
# bspc config urgent_border_color "#B58900"
# bspc config presel_border_color "#26E2FF"

# set resolution (uw)
xrandr --output DP-2 --mode 5120x2160

# autostart applications
sxhkd &
picom --config ~/.config/picom/picom.conf &
nitrogen --restore &
dunst &
polybar &
