#! /bin/sh

# Start settings early
xrdb -merge ~/.Xresources
pgrep -x xsettingsd >/dev/null || xsettingsd &

# Hotkeys (only once)
pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor -d      

bspc config border_width         3
bspc config window_gap           20
bspc config top_padding          55
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config normal_border_color  "#363a4f"
bspc config focused_border_color "#8aadf4"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Thunar state=floating

# autostart applications
picom --config ~/.config/picom/picom.conf &
feh --bg-fill ~/Pictures/wallpapers/laptop/catppuccin-macchiato/spaceman.png &
dunst &
polybar &

